-- Nexora Technologies contact-message database
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null check (char_length(full_name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 160),
  phone text,
  company text,
  service text not null check (service in ('Website','Web / Mobile App','Business Software','AI Solution','Automation')),
  message text not null check (char_length(message) between 1 and 3000)
);

create index if not exists contact_messages_created_at_idx on public.contact_messages (created_at desc);

-- Stores the Supabase Auth user IDs that are allowed to view messages.
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;
alter table public.admins enable row level security;

-- Public website visitors may submit a contact message.
drop policy if exists "Public can submit contact messages" on public.contact_messages;
create policy "Public can submit contact messages"
on public.contact_messages
for insert
to anon, authenticated
with check (true);

-- Only users listed in public.admins can read messages.
drop policy if exists "Admins can read contact messages" on public.contact_messages;
create policy "Admins can read contact messages"
on public.contact_messages
for select
to authenticated
using (
  exists (
    select 1 from public.admins a
    where a.user_id = auth.uid()
  )
);

-- Admins can see only their own authorization row.
drop policy if exists "Admins can read own admin row" on public.admins;
create policy "Admins can read own admin row"
on public.admins
for select
to authenticated
using (user_id = auth.uid());

-- No public insert/update/delete policy exists on admins.
-- Add an admin user after creating that user in Supabase Authentication:
-- insert into public.admins (user_id) values ('PASTE_AUTH_USER_UUID_HERE');
